### PR TITLE
view list of tags

### PR DESCRIPTION
**Pull request by hchickey**
Created:
TagRepository 
ITagRepository
TagController
Tag Views Index

Check by: 
running application
login to admin
got to menu
click on tags
and should see a list of all the tags

### CODE REVIEW

**Comment by sseals1** [comment]
Checked functionality for the View all Tags. Everything looks good!

**Comment by sseals1** [comment]
Tested Tags View and all displays as outlined.

**Comment by bmangum8** [comment]
👍

**Comment by bmangum8** [comment]
👍

**Pull request merged**
